# Copyright 2023-2024 Shinami Corp.
# SPDX-License-Identifier: Apache-2.0

repos:
  - repo: local
    hooks:
      - id: build
        name: Build
        language: script
        entry: >-
          ci_build.sh
        pass_filenames: false
        stages: [pre-commit]
      - id: lint
        name: Lint
        language: system
        entry: npm run lint
        pass_filenames: false
        stages: [pre-commit]
